### ISSUE TITLE
Can you please provide an example on how to use?

### ISSUE THREAD

**Issue by paulpreibisch** [driannaude/angular-sha#1]
Hi there, I am interested in contributing, can u please provide a usage example?

**Comment by vjasterix** [comment]
I'm getting an unkown provider error.

**Comment by EugeneButusov** [comment]
@paulpreibisch, after method is integrated, this code is working for me:
```
$sha.setConfig();
$sha.hmac(user.email, SECRET);
```

**Comment by EugeneButusov** [comment]
@vjasterix, for me `module not found` returned error, because I've used `ngSha` name (as in repo), but bower has `dn.sha` name.
Also, from sources I haven't seen that it has provider.

**Comment by driannaude** [comment]
@paulpreibisch apologies for taking a year+ in getting back to you, i must've missed notifications for this repo 😕  . I'll update the readme with a usage example soon.

**Comment by driannaude** [comment]
@EugeneButusov appreciate the help again mate, it's a bit of a shambles at the moment, a lot can be done to improve the quality and usefulness of this repo. @vjasterix I'll be updating (read: adding) the documentation soon, which will hopefully clarify a few things.

**Comment by driannaude** [comment]
@paulpreibisch I've added a more detailed README with some usage examples. I'm happy to catch up at some point if you still want to contribute, although after a year it's not an issue if you don't. 😄

**Comment by driannaude** [comment]
Closing this as resolved. @vjasterix if you still require assistance for your issue please create a new issue.
