### ISSUE TITLE
Small bug correction: 

### ISSUE THREAD

**Issue by vjasterix** [driannaude/angular-sha#2]
line 115 should be (did not previously use data): 

`return _doHMAC(self.config.algorithm, self.config.inputType, self.config.returnType, data, secret, self.config.secretType, data);`

**Comment by EugeneButusov** [comment]
@vjasterix, I've put fix there: https://github.com/driannaude/angular-sha/pull/3
@driannaude please check it out.

**Comment by driannaude** [comment]
good catch @vjasterix sorry it's taken me this long to see this, I've not really used/maintained this much in the past year. @EugeneButusov thanks for the PR, merging it soon. 👍 

Closed - Fixed by #3
